"""Consolidate EVERY social URL seen across all snapshots into one master registry.

The gap this fixes: IG/FB posts are pulled by Apify scraping the profile, so
their individual URLs land inside the snapshot JSON but never in the manifest.
Anyone reading only the manifest (e.g. Gamma at handoff) sees a fraction of the
real tracked content. This scans every snapshot across every episode, dedupes,
and emits a single durable registry so nothing is invisible.

Output:
  SOCIAL_URL_REGISTRY.csv   — one row per unique URL (platform, title, counts, seen-range)
  SOCIAL_URL_REGISTRY.md    — human-readable, grouped by platform, for handoff

Usage:
  MCP/.venv/bin/python Projects/talking_downey/kpis/build_url_registry.py
"""
from __future__ import annotations
import csv
import json
from pathlib import Path

KPIS = Path(__file__).parent
EPISODES = KPIS / "episodes_public"
OUT_CSV = KPIS / "SOCIAL_URL_REGISTRY.csv"
OUT_MD = KPIS / "SOCIAL_URL_REGISTRY.md"


def snap_sort_key(p: Path):
    # tag like t0, t1 ... t10 — sort numerically, fall back to mtime
    stem = p.stem
    if stem.startswith("t") and stem[1:].isdigit():
        return (0, int(stem[1:]))
    return (1, p.stat().st_mtime)


def main():
    registry: dict[str, dict] = {}  # url -> record

    episode_dirs = sorted(d for d in EPISODES.iterdir() if d.is_dir())
    for ep in episode_dirs:
        snaps_dir = ep / "snapshots"
        if not snaps_dir.exists():
            continue
        for snap in sorted(snaps_dir.glob("*.json"), key=snap_sort_key):
            try:
                data = json.loads(snap.read_text())
            except Exception:
                continue
            tag = snap.stem
            for r in data.get("records", []):
                url = r.get("url")
                if not url:
                    continue
                cur = registry.get(url)
                if cur is None:
                    registry[url] = {
                        "url": url,
                        "platform": r.get("platform", "?"),
                        "title": (r.get("title") or "").replace("\n", " ").strip()[:120],
                        "episode": ep.name,
                        "first_seen": tag,
                        "last_seen": tag,
                        "latest_views": r.get("view_count"),
                        "latest_likes": r.get("like_count"),
                        "latest_comments": r.get("comment_count"),
                    }
                else:
                    cur["last_seen"] = tag  # snaps iterated in order, so last wins
                    # keep the most recent non-null metrics
                    if r.get("view_count") is not None:
                        cur["latest_views"] = r.get("view_count")
                    if r.get("like_count") is not None:
                        cur["latest_likes"] = r.get("like_count")
                    if r.get("comment_count") is not None:
                        cur["latest_comments"] = r.get("comment_count")

    rows = list(registry.values())
    # sort: platform, then views desc
    rows.sort(key=lambda x: (x["platform"], -(x["latest_views"] or 0)))

    # CSV
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=[
            "platform", "title", "url", "episode",
            "first_seen", "last_seen", "latest_views", "latest_likes", "latest_comments",
        ])
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in w.fieldnames})

    # MD (handoff-friendly, grouped by platform)
    from collections import Counter, defaultdict
    by_plat = defaultdict(list)
    for r in rows:
        by_plat[r["platform"]].append(r)
    counts = Counter(r["platform"] for r in rows)

    lines = [
        "# Talking Downey — Social URL Registry",
        "",
        "> Master list of EVERY social post URL captured across all KPI snapshots.",
        "> Auto-generated by `build_url_registry.py`. This is the complete tracked set —",
        "> the per-episode `manifest.yaml` only holds the seed URLs (YouTube + TikTok);",
        "> IG/FB posts arrive via Apify profile scrape and live only in snapshots, so this",
        "> registry is the single source of truth for handoff.",
        "",
        f"**Total unique URLs: {len(rows)}**  —  " +
        " · ".join(f"{p}: {c}" for p, c in counts.most_common()),
        "",
    ]
    for plat in ["youtube", "tiktok", "instagram", "facebook"]:
        items = by_plat.get(plat, [])
        if not items:
            continue
        lines.append(f"## {plat.title()} ({len(items)})")
        lines.append("")
        lines.append("| Views | Title | URL | seen |")
        lines.append("|---:|---|---|---|")
        for r in items:
            v = f"{r['latest_views']:,}" if isinstance(r["latest_views"], int) else "—"
            title = r["title"] or "(no title)"
            lines.append(f"| {v} | {title} | {r['url']} | {r['first_seen']}→{r['last_seen']} |")
        lines.append("")
    OUT_MD.write_text("\n".join(lines))

    print(f"✓ {len(rows)} unique URLs across {len(episode_dirs)} episode(s)")
    for p, c in counts.most_common():
        print(f"    {p}: {c}")
    print(f"✓ {OUT_CSV}")
    print(f"✓ {OUT_MD}")


if __name__ == "__main__":
    main()
